name: feed
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  dotted_border: ^3.0.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.2.0
  get: ^4.7.2
  go_router: ^15.2.4
  http: ^1.4.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - lib/assets/images/image 8.png
    - lib/assets/images/image-upload.png
    - lib/assets/svgs/user_switch.svg
    - lib/assets/svgs/user_question.svg
    - lib/assets/svgs/up_arrow.svg
    - lib/assets/svgs/share.svg
    - lib/assets/svgs/reply.svg
    - lib/assets/svgs/thumbs_up.svg
    - lib/assets/svgs/search.svg
    - lib/assets/svgs/send.svg
